name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'

      - name: Navigate to backend directory
        working-directory: backend/my-own-todo-app
        run: |
          mvn -B package

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        working-directory: backend/my-own-todo-app
        run: |
          docker build -f src/main/docker/Dockerfile.jvm -t ghcr.io/efouret/my-own-todo-app:latest .

      - name: Push Docker image to GitHub Container Registry
        working-directory: backend/my-own-todo-app
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          docker push ghcr.io/efouret/my-own-todo-app:latest