name: Build and Push Docker Image

on:
  pull_request:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'
          cache-dependency-path: 'backend/my-own-todo-app/pom.xml'

      - name: Navigate to backend directory
        working-directory: backend/my-own-todo-app
        run: |
          mvn -B package
